Importing Libraries

In [215]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier

Loading Train Set

In [216]:
train = pd.read_csv(r'C:\Users\pc\Documents\MACHINE LEARNING\Codveda-Internship\KNN Classifier\datasets\iris train set.csv')
train.head()

sepal_length  sepal_width  petal_length  petal_width    species
0           6.4          3.1           5.5          1.8  virginica
1           4.6          3.2           1.4          0.2     setosa
2           5.6          2.8           4.9          2.0  virginica
3           5.2          3.5           1.5          0.2     setosa
4           5.0          3.6           1.4          0.2     setosa

Feature Selection

In [217]:
x = train.drop('species', axis=1)
y = train['species']

Train Set Splitting 

In [218]:
x_train, x_validate, y_train, y_validate = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

Model Development

KNN when K=5 

In [219]:
pipe1 = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=5))
    ]
)

In [220]:
pipe1.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

In [221]:
y_knn5_pred = pipe1.predict(x_validate)

Accuracy Score

In [222]:
ac5 = accuracy_score(y_validate, y_knn5_pred)
print(f'Accuracy Score when KNN=7 is: {ac5}')

Accuracy Score when KNN=7 is: 0.9166666666666666


Confusion Matrix

In [223]:
confusion_matrix(y_validate, y_knn5_pred)

array([[8, 0, 0],
       [0, 7, 1],
       [0, 1, 7]])

Classification Report

In [224]:
CR_k5 = classification_report(y_validate, y_knn5_pred, output_dict=True)
CR_k5 = pd.DataFrame(CR_k5)
CR_k5

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0       0.875      0.875  0.916667   0.916667      0.916667
recall        1.0       0.875      0.875  0.916667   0.916667      0.916667
f1-score      1.0       0.875      0.875  0.916667   0.916667      0.916667
support       8.0       8.000      8.000  0.916667  24.000000     24.000000

KNN when K=3

In [225]:
pipe2 = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=3))
    ]
)

In [226]:
pipe2.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [227]:
y_knn3_pred = pipe2.predict(x_validate)

Accuracy Score

In [228]:
ac3 = accuracy_score(y_validate, y_knn3_pred)
print(f'Accuracy Score when KNN=7 is: {ac3}')

Accuracy Score when KNN=7 is: 0.9166666666666666


Confusion Matrix

In [229]:
confusion_matrix(y_validate, y_knn3_pred)

array([[8, 0, 0],
       [0, 7, 1],
       [0, 1, 7]])

Classification Report

In [230]:
CR_k3 = classification_report(y_validate, y_knn3_pred, output_dict=True)
CR_k3 = pd.DataFrame(CR_k3)
CR_k3

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0       0.875      0.875  0.916667   0.916667      0.916667
recall        1.0       0.875      0.875  0.916667   0.916667      0.916667
f1-score      1.0       0.875      0.875  0.916667   0.916667      0.916667
support       8.0       8.000      8.000  0.916667  24.000000     24.000000

KNN when K=7

In [231]:
pipe3 = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=7))
    ]
)

In [232]:
pipe3.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=7))])

In [233]:
y_knn7_pred = pipe3.predict(x_validate)

Accuracy Score

In [234]:
ac7 = accuracy_score(y_validate, y_knn7_pred)
print(f'Accuracy Score when KNN=7 is: {ac7}')

Accuracy Score when KNN=7 is: 0.9583333333333334


Confusion Matrix

In [235]:
confusion_matrix(y_validate, y_knn7_pred)

array([[8, 0, 0],
       [0, 7, 1],
       [0, 0, 8]])

Classification Report

In [236]:
CR_k7 = classification_report(y_validate, y_knn7_pred, output_dict=True)
CR_k7 = pd.DataFrame(CR_k7)
CR_k7

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0    1.000000   0.888889  0.958333   0.962963      0.962963
recall        1.0    0.875000   1.000000  0.958333   0.958333      0.958333
f1-score      1.0    0.933333   0.941176  0.958333   0.958170      0.958170
support       8.0    8.000000   8.000000  0.958333  24.000000     24.000000

In [237]:
joblib.dump(pipe1, 'knn1_pipeline.pkl')
joblib.dump(pipe2, 'knn2_pipeline.pkl')
joblib.dump(pipe3, 'knn3_pipeline.pkl')

['knn3_pipeline.pkl']

Loading Test Set

In [238]:
test = pd.read_csv(r'C:\Users\pc\Documents\MACHINE LEARNING\Codveda-Internship\KNN Classifier\datasets\iris test set.csv')
test.head()

sepal_length  sepal_width  petal_length  petal_width     species
0           6.1          3.0           4.9          1.8   virginica
1           5.5          2.3           4.0          1.3  versicolor
2           6.7          3.1           5.6          2.4   virginica
3           5.1          3.8           1.5          0.3      setosa
4           4.9          2.5           4.5          1.7   virginica

Feature Selection

In [239]:
z_test= test.drop('species', axis=1)
y_test = test['species']

Best Performing Model: KNN when k=7

In [240]:
y_test_knn7_pred = pipe3.predict(z_test)

In [241]:
ac7_test = accuracy_score(y_test, y_test_knn7_pred)
print(f'Accuracy Score when KNN=7 is: {ac7_test}')

Accuracy Score when KNN=7 is: 0.9333333333333333


In [242]:
confusion_matrix(y_test, y_test_knn7_pred)

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  1,  8]])

In [243]:
CR_k7 = classification_report(y_test, y_test_knn7_pred, output_dict=True)
CR_k7 = pd.DataFrame(CR_k7)
CR_k7

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0         0.9   0.888889  0.933333    0.92963      0.933333
recall        1.0         0.9   0.888889  0.933333    0.92963      0.933333
f1-score      1.0         0.9   0.888889  0.933333    0.92963      0.933333
support      11.0        10.0   9.000000  0.933333   30.00000     30.000000